hooks                                   usr/share/initramfs-tools
scripts/30mini-iso-menu                 usr/share/initramfs-tools/scripts/casper-premount
scripts/iso-menu-session                usr/lib/mini-iso-tools/usr/bin
scripts/regions/get_memmap_directive    usr/lib/mini-iso-tools/usr/bin
iso-chooser-menu                        usr/lib/mini-iso-tools/usr/bin
share/subiquity.psf                     usr/lib/mini-iso-tools/usr/lib/mini-iso-tools
