#!/bin/sh

set -e

# ensures we have the unicode glyphs - half-blocks, right arrow
/usr/bin/setfont /usr/lib/mini-iso-tools/subiquity.psf

cdimage_json=/cdimage.json
wget -O $cdimage_json \
    https://cdimage.ubuntu.com/streams/v1/com.ubuntu.cdimage.daily:ubuntu-server.json

/usr/lib/mini-iso-tools/iso-chooser-menu /out.vars $cdimage_json
